name: Build and Push Docker Image

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      registry: ghcr.io
      images: ghcr.io/${{ github.repository }}
      registry_username: ${{ github.actor }}
    secrets:
      registry_password: ${{ secrets.GITHUB_TOKEN }}
