name: Build and Push to Docker Hub

on:
  push:
    branches: [master]
    tags:
      - 'v*'
  pull_request:
    branches: [master]

permissions:
  contents: read
  packages: write

env:
  REGISTRY_USERNAME: ${{ vars.DOCKERHUB_USERNAME || github.actor }}

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
    with:
      registry: docker.io
      images: ${{ github.repository }}
      registry_username: ${{ vars.DOCKERHUB_USERNAME || github.actor }}
    secrets:
      registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
